# Generated by Django 5.2 on 2025-05-02 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0002_comment_post_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='photo_url',
        ),
        migrations.AddField(
            model_name='author',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='authors_photos'),
        ),
    ]
